### ISSUE TITLE
Cannot change Translation and Scale of Actors with an RMCStatic

### ISSUE THREAD

**Issue by Russell-Newton** [KoderzUnreal/RuntimeMeshComponent#187]
Every time I try to move, rotate, or rescale an actor with an RMCStatic, the RMCStatic disappears from the editor. In the Output Log, I see the message:
```
RuntimeMeshLog: Error: Cannot bind a provider to a RuntimeMesh after it has been bound to another provider.
```
I have not been able to trace the source of this message, and I have no idea how to diagnose this.

I am trying to make a Blueprint that contains an RMCStatic, and I can place it into the world with the initial drag-and-drop, but I cannot move it to where I want in the level.

In case I'm doing something wrong, this is what the Blueprint Editor looks like
![RMCStatic Blueprint Editor](https://user-images.githubusercontent.com/18690062/89137800-596ca080-d507-11ea-8623-ec1c89da55c7.png)

**Comment by Koderz** [comment]
Hey @Russell-Newton ,

What version of the plugin are you using? did you get it from the Marketplace or GitHub?   That message I think should be gone now in the GitHub version I don't know if those fixes have made it to the Marketplace yet.

**Comment by Russell-Newton** [comment]
I'm using the latest version on GitHub, 4.1.3, with Unreal Engine 4.25.3.

**Comment by Koderz** [comment]
Ok, you're using the actual release version? That's the same as the marketplace version. I think that should fixed in master branch if you want to try that, that's the version I'm going to push to the MP and 4.1.4 after I fix a couple other things.

**Comment by Russell-Newton** [comment]
Correct. I'm using the latest one on the releases page on GitHub.

**Comment by Russell-Newton** [comment]
It looks like the mesh still disappears when I use the version on the master branch. However, it no longer says the message `RuntimeMeshLog: Error: Cannot bind a provider to a RuntimeMesh after it has been bound to another provider.`

**Comment by Russell-Newton** [comment]
I've put the contents from the master branch into my project, and I no longer see the message `RuntimeMeshLog: Error: Cannot bind a provider to a RuntimeMesh after it has been bound to another provider.` However, I have noticed a few things. Consider the picture:
![RMCStatic 8-7-2020](https://user-images.githubusercontent.com/18690062/89668923-98ef1000-d8ac-11ea-87b1-887a73fd0bd8.jpg)
1. I can move the `RMCStatic (Inherited)` using the translation controls in the editor window without any problems.
2. I can move the root `StaticMeshComponent (Inherited)` using the translation controls in the editor window without any problems.
3. I cannot move either component with the transform properties in the component details toolbox without the mesh disappearing.
4. I cannot move the entire component `Terrain(self)` without the mesh disappearing.
5. If I undo a translation made with the translation controls in the editor window, the mesh disappears.
6. I never once see the message `RuntimeMeshLog: Error: Cannot bind a provider to a RuntimeMesh after it has been bound to another provider.`

**Comment by zacharygriffee** [comment]
I am getting the same issue. The fix didn't fix. 

![image](https://user-images.githubusercontent.com/5599507/91380444-fcf15e00-e7f2-11ea-9385-b229c925083c.png)

The runtime static mesh (which is a floor) is suppose to be to the left of the static mesh floor in the picture but its invisible because I set the mobility to moveable.

**Comment by zacharygriffee** [comment]
Just wondering if there is plans to fix this issue?
